# frozen_string_literal: true

# These tasks were used to revert some incorrectly imported answers to plans.
# The imports originated from an external system that had a bug in its
# integration logic causing the data to be messed up. All mistaken updates were
# done 2026-02-13 which is the cutoff for the revert logic.
namespace :plananswers do
  desc "Creates a preview of the data to be reverted"
  task :preview, [:component_id, :outfile] => [:environment] do |_t, args|
    c = plans_component(args.component_id)
    unless c
      puts "Invalid component provided: #{args.component_id}."
      next
    end

    if File.exist?(args.outfile)
      puts "File already exists at: #{args.outfile}"
      next
    end

    exporter = Decidim::Exporters::Excel.new(dataset(c), Decidim::Exporters::Serializer)
    export_data = exporter.export
    File.binwrite(args.outfile, export_data.read)

    puts "Data written to: #{args.outfile}"
  end

  desc "Reverts the answers to the previous state"
  task :revert, [:component_id] => [:environment] do |_t, args|
    c = plans_component(args.component_id)
    unless c
      puts "Invalid component provided: #{args.component_id}."
      next
    end

    puts "Reverting plans"
    puts "id;state;answer/fi;answer/sv;answer/en;state_before;answer_before/fi;answer_before/sv;answer_before/en"

    multiline_text = lambda do |text|
      if text
        escaped = text.gsub("\"", "\"\"")
        %("#{escaped}")
      else
        ""
      end
    end

    languages = %w(fi sv en).freeze
    dataset(c).each do |data|
      plan = Decidim::Plans::Plan.find(data[:id])
      answer_before = plan.answer || {}

      out = [
        plan.id,
        data[:state],
        *languages.map { |code| multiline_text.call(data[:answer][code]) },
        plan.state,
        *languages.map { |code| multiline_text.call(answer_before[code]) }
      ]
      puts out.join(";")

      plan.update!(
        state: data[:state],
        answer: data[:answer]
      )
    end
  end

  def plans_component(component_id)
    c = Decidim::Component.find_by(id: component_id)
    return unless c
    return unless c.manifest_name == "plans"

    c
  end

  def each_plan(component)
    Decidim::Plans::Plan.where(component: component).published.not_hidden.except_withdrawn.find_each do |plan|
      yield plan
    end
  end

  # rubocop:disable Metrics/CyclomaticComplexity, Metrics/PerceivedComplexity
  def dataset(component)
    cutoff = Time.parse("2026-02-13T00:00:00+0000").utc
    target_keys = %w(state answer).freeze
    empty_content = { "fi" => "", "sv" => "", "en" => "" }
    set = []
    each_plan(component) do |plan|
      changed_version = nil
      changes = nil
      plan.versions.reverse.each do |version|
        next unless version.object_changes

        # The version change data is trusted as it is generated by PaperTrail
        # and the users cannot control the data types that get serialized.
        changes = YAML.unsafe_load(version.object_changes)
        next if target_keys.none? { |key| changes.has_key?(key) }

        changed_version = version
        break
      end
      next unless changed_version
      next unless changed_version.created_at >= cutoff

      changes ||= {}

      previous_state = nil
      previous_state = changes["state"][0] if changes["state"]
      previous_answer = nil
      previous_answer = JSON.parse(changes["answer"][0]) if changes["answer"] && changes["answer"][0].is_a?(String)

      set << {
        id: plan.id,
        title: empty_content.merge(plan.title),
        state: previous_state || plan.state,
        answer: empty_content.merge(previous_answer || {})
      }
    end

    set
  end
  # rubocop:enable Metrics/CyclomaticComplexity, Metrics/PerceivedComplexity
end
