inherit_from:
  - .rubocop_ruby.yml
  - .rubocop_rails.yml

# Additions to the default rules
inherit_mode:
  merge:
    - Include
    - Exclude

AllCops:
  Include:
    - .simplecov
    - "**/*.rb"
    - "**/*.rake"
    - "**/*.gemspec"
    - "**/*.ru"
    - "**/Gemfile"
    - "**/Rakefile"
  Exclude:
    - "**/vendor/**/*"
    - "development_app/**/*"
    - "spec/decidim_dummy_app/**/*"
    - "node_modules/**/*"
    - "tmp/**/*"

Rails/ActionFilter:
  Include:
    - app/controllers/**/*.rb

Rails/EnumUniqueness:
  Include:
    - app/models/**/*.rb

Rails/Exit:
  Include:
    - app/**/*.rb
    - config/**/*.rb
    - lib/**/*.rb
  Exclude:
    - lib/**/*.rake

Rails/FindEach:
  Include:
    - app/models/**/*.rb

Rails/HasAndBelongsToMany:
  Include:
    - app/models/**/*.rb

Rails/HasManyOrHasOneDependent:
  Include:
    - app/models/**/*.rb

Rails/Output:
  Include:
    - app/**/*.rb
    - config/**/*.rb
    - db/**/*.rb
    - lib/**/*.rb

Rails/ReadWriteAttribute:
  Include:
    - app/models/**/*.rb

Rails/ScopeArgs:
  Include:
    - app/models/**/*.rb

Rails/Validation:
  Include:
    - app/models/**/*.rb
