require: rubocop-rails

Rails:
  Enabled: true

Rails/ActionFilter:
  Include:
    - app/controllers/**/*.rb

Rails/ContentTag:
  Enabled: false

Rails/CreateTableWithTimestamps:
  Enabled: false

Rails/EnumUniqueness:
  Include:
    - app/models/**/*.rb

Rails/Exit:
  Include:
    - app/**/*.rb
    - config/**/*.rb
    - lib/**/*.rb
  Exclude:
    - lib/**/*.rake

Rails/FindBy:
  Include:
    - "**/*.rb"

Rails/FindEach:
  Include:
    - app/models/**/*.rb

Rails/HasAndBelongsToMany:
  Include:
    - app/models/**/*.rb

Rails/HasManyOrHasOneDependent:
  Include:
    - app/models/**/*.rb

Rails/InverseOf:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Include:
    - app/controllers/**/*.rb

Rails/NotNullColumn:
  Enabled: false

Rails/Output:
  Include:
    - app/**/*.rb
    - config/**/*.rb
    - db/**/*.rb
    - lib/**/*.rb
  Exclude:
    - decidim-core/db/seeds.rb
    - decidim-core/lib/decidim/core.rb
    - decidim-core/lib/decidim/component_manifest.rb
    - decidim-core/lib/decidim/participatory_space_manifest.rb
    - decidim-system/db/seeds.rb
    - decidim-templates/db/seeds.rb

Rails/OutputSafety:
  Enabled: false

Rails/Pluck:
  Enabled: false

Rails/RakeEnvironment:
  Enabled: false

Rails/ReadWriteAttribute:
  Include:
    - app/models/**/*.rb

Rails/ReversibleMigration:
  Enabled: false

Rails/ScopeArgs:
  Include:
    - app/models/**/*.rb

Rails/SkipsModelValidations:
  Enabled: true

Rails/Validation:
  Include:
    - app/models/**/*.rb
