# frozen_string_literal: true

require "omniauth/strategies/openid_connect_helsinki"
require "helsinki/devise_failure_app"

Devise.setup do |config|
  # ==> Warden configuration
  # Needed to fix:
  # https://github.com/decidim/decidim/issues/4660
  config.warden do |manager|
    manager.failure_app = Helsinki::DeviseFailureApp
  end

  config.secret_key = Rails.application.secrets.secret_key_devise.inspect

  ###################################
  # Setup Tunnistamo authentication #
  ###################################
  server_uri = Rails.application.config.tunnistamo_auth_server
  if server_uri
    urlopts = Rails.application.config.action_controller.default_url_options

    # Fallback to localhost (development, testing, etc.)
    app_root_url = begin
      if urlopts && urlopts[:host]
        url = urlopts[:protocol] || (urlopts[:port] == 443 ? "https" : "http")
        url += "://#{urlopts[:host]}"
        url += ":#{urlopts[:port]}" if urlopts[:port] && !urlopts[:port].to_s.match(/^80|443$/)
        url
      else
        "http://localhost:3000"
      end
    end

    client_id = Rails.application.secrets.dig(:omniauth, :tunnistamo, :app_id)
    client_secret = Rails.application.secrets.dig(:omniauth, :tunnistamo, :app_secret)

    auth_uri = URI.parse(server_uri)

    config.omniauth(
      :openid_connect_helsinki,
      name: :tunnistamo,
      scope: [:openid, :email, :profile],
      response_type: :code,
      issuer: "#{server_uri}/openid",
      discovery: true,
      client_options: {
        port: auth_uri.port,
        scheme: auth_uri.scheme,
        host: auth_uri.host,
        identifier: client_id,
        secret: client_secret,
        redirect_uri: "#{app_root_url}/users/auth/tunnistamo/callback"
      },
      post_logout_redirect_uri: app_root_url
    )

    # Make sure the SWD discovery requests (generated by the openid_connect gem)
    # will succeed also with the "http" URI scheme, so it does not force the
    # authentication endpoint to be secured (e.g. during development).
    SWD.url_builder = URI::HTTP if server_uri.match?(%r{^http://})
  end
end
