test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

microsoft:
  service: AzureStorage
  storage_account_name: <%= ENV["AZURE_BLOB_STORAGE_ACCOUNT"] %>
  storage_access_key: <%= ENV["AZURE_BLOB_STORAGE_KEY"] %>
  container: <%= ENV["AZURE_BLOB_STORAGE_CONTAINER"] %>

mirror:
  service: Mirror
  primary: local
  mirrors: [microsoft]
